---
# tasks/cache.yml

- name: ocStore | Rollback | Enumerate cache files
  find:
    paths: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
    file_type: "any"
    patterns: "{{ item.patterns }}"
    use_regex: True
  with_flattened:
    - "{{ ocstore_shared_cache_path }}"
  register: ocstore_cache_files
  when: ocstore_shared_cache_clean is defined and ocstore_shared_cache_clean == "yes"
  no_log: True

- name: ocStore | Rollback | Delete cache files
  file:
    path: "{{ item.1.path }}"
    state: absent
  with_subelements:
     - "{{ ocstore_cache_files.results }}"
     - files
  when: ocstore_shared_cache_clean is defined and ocstore_shared_cache_clean == "yes"
  no_log: True
