---
# tasks/cleanup.yml

- name: ocStore | Deploy | Ensure symlinks for shared template files are valid
  file:
    state: link
    path: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
    src: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/{{ ocstore_shared_dir }}/{{ item.path }}"
  with_flattened:
    - "{{ ocstore_shared_template_files }}"

- name: ocStore | Rollback | Read REVISION file from previous release
  shell: cat "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/REVISION"
  register: ocstore_previous_release_revision
  changed_when: false

- name: ocStore | Rollback | Get rollback release version
  set_fact:
    ocstore_rollback_revision: "{{ ocstore_previous_release_revision.stdout if ocstore_previous_release_revision.stdout[:1] != '+' and ocstore_previous_release_revision.stdout[:1] != '-' else ocstore_previous_release_revision.stdout[1:] }}"

- name: ocStore | Rollback | Mark previous release as rolled back
  copy:
    content: "-{{ ocstore_rollback_revision }}"
    dest: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/REVISION"
    mode: "660"
    group: "{{ ocstore_www_owner_group }}"
    owner: "{{ ocstore_www_owner_user }}"
  become: yes

- name: ocStore | Rollback | Change symlink from current release to previous one
  shell: ln -s "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/{{ ocstore_public_dir }}" "{{ ocstore_www_root }}/{{ ocstore_current_dir }}_tmp" && mv -Tf "{{ ocstore_www_root }}/{{ ocstore_current_dir }}_tmp" "{{ ocstore_www_root }}/{{ ocstore_current_dir }}"

#- name: ocStore | Rollback | Change symlink from current release to previous one
#  file:
#    state: link
#    path: "{{ ocstore_www_root }}/{{ ocstore_current_dir }}"
#    src: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/{{ ocstore_public_dir }}"

#- name: ocStore | Rollback | Restart services
#  service:
#    name: "{{ item }}"
#    state: "reloaded"
#  with_items:
#    - "php7.0-fpm"
#  become: "yes"

- name: ocStore | Rollback | Remove rolled back version
  file:
    state: absent
    path: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_current_release_version.stdout }}"
  when: ocstore_remove_rolled_back
