---
# tasks/cleanup.yml

- name: ocStore | Deploy | Ensure symlinks for shared template files are valid
  file:
    state: link
    path: "{{ ocstore_www_root }}/{{ ocstore_shared_dir }}/{{ item.path }}"
    src: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/{{ ocstore_shared_dir }}/{{ item.path }}"
  with_flattened:
    - "{{ ocstore_shared_template_files }}"

- name: ocStore | Rollback | Change symlink from current release to previous one
  file:
    state: link
    path: "{{ ocstore_www_root }}/{{ ocstore_current_dir }}"
    src: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/{{ ocstore_public_dir }}"

- name: ocStore | Rollback | Restart services
  service:
    name: "{{ item }}"
    state: "restarted"
  with_items:
    - "php7.0-fpm"
  become: "yes"

- name: ocStore | Rollback | Remove rolled back version
  file:
    state: absent
    path: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_current_release_version.stdout }}"
  when: ocstore_remove_rolled_back
