---
# tasks/cleanup.yml

- name: ocStore | Rollback | Change symlink from current release to previous one
  file:
    state: link
    path: "{{ ocstore_www_root }}/{{ ocstore_current_dir }}"
    src: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_rollback_release_version }}/{{ ocstore_public_dir }}"

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
  become: yes

- name: ocStore | Rollback | Remove rolled back version
  file:
    state: absent
    path: "{{ ocstore_www_root }}/{{ ocstore_releases_dir }}/{{ ocstore_current_release_version.stdout }}"
  when: ocstore_remove_rolled_back
