---
# tasks/main.yml

- import_tasks: symlink.yml
  when: ocstore_environment != 'development'

- import_tasks: cache.yml
  when: ocstore_environment != 'development'

- import_tasks: cleanup.yml
  when: ocstore_environment != 'development'
