---
# tasks/restart.yml

- name: restart apache2
  service:
    name: apache2
    state: restarted
  become: yes

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
  become: yes
